// core/errors/errorTypes.ts
export enum ErrorCode {
  // Auth Errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_CONFIRMED = 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_RATE_LIMIT_EXCEEDED = 'AUTH_RATE_LIMIT_EXCEEDED',
  AUTH_TENANT_MISMATCH = 'AUTH_TENANT_MISMATCH',
  AUTH_STAFF_NOT_FOUND = 'AUTH_STAFF_NOT_FOUND',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  
  // Validation Errors
  VALIDATION_REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_EMAIL = 'VALIDATION_INVALID_EMAIL',
  VALIDATION_PASSWORD_MISMATCH = 'VALIDATION_PASSWORD_MISMATCH',
  VALIDATION_WEAK_PASSWORD = 'VALIDATION_WEAK_PASSWORD',
  
  // Network Errors
  NETWORK_CONNECTION_ERROR = 'NETWORK_CONNECTION_ERROR',
  NETWORK_TIMEOUT = 'NETWORK_TIMEOUT',
  
  // Database Errors
  DB_CONFLICT = 'DB_CONFLICT',
  DB_NOT_FOUND = 'DB_NOT_FOUND',
  
  // Unknown
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export interface ErrorDetails {
  field?: string;
  originalError?: any;
  timestamp?: string;
  userMessage?: string;
}